package com.acdfirstproject

const val MILLISECONDS_INTENT = "MILLISECONDS_INTENT"
const val FIRST_TEAM_INTENT: String = "FIRST_TEAM"
const val SECOND_TEAM_INTENT: String = "SECOND_TEAM"
const val BROADCAST_ACTION: String = "BROADCAST_ACTION"
const val WINNER_NAME_INTENT: String = "WINNER_NAME_INTENT"
const val RESULT_GAME_INTENT: String = "RESULT_GAME_INTENT"



const val MILLI_SECOND_FOR_TIMER = "MILLI_SECOND_FOR_TIMER"